//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetRoleBasedSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infra_by_track
    {
        public string t { get; set; }
        public string Name { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
