//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetRoleBasedSecurity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LineEntities : DbContext
    {
        public LineEntities()
            : base("name=LineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Contribution> Admin_Contribution { get; set; }
        public virtual DbSet<Admin_Contribution19> Admin_Contribution19 { get; set; }
        public virtual DbSet<Admin_Contribution20> Admin_Contribution20 { get; set; }
        public virtual DbSet<Close> Closes { get; set; }
        public virtual DbSet<Drill_er> Drill_er { get; set; }
        public virtual DbSet<Drill_mc> Drill_mc { get; set; }
        public virtual DbSet<Drill_pc> Drill_pc { get; set; }
        public virtual DbSet<er> ers { get; set; }
        public virtual DbSet<ER_overall> ER_overall { get; set; }
        public virtual DbSet<Infra_by_track> Infra_by_track { get; set; }
        public virtual DbSet<Infraction> Infractions { get; set; }
        public virtual DbSet<Line_Close> Line_Close { get; set; }
        public virtual DbSet<Line_Open> Line_Open { get; set; }
        public virtual DbSet<mc> mcs { get; set; }
        public virtual DbSet<MC_overall> MC_overall { get; set; }
        public virtual DbSet<Open> Opens { get; set; }
        public virtual DbSet<pc> pcs { get; set; }
        public virtual DbSet<PC_overall> PC_overall { get; set; }
        public virtual DbSet<Ron> Rons { get; set; }
        public virtual DbSet<Ron_overall> Ron_overall { get; set; }
        public virtual DbSet<RQ> RQs { get; set; }
        public virtual DbSet<RQ_overall> RQ_overall { get; set; }
        public virtual DbSet<Total_Area> Total_Area { get; set; }
        public virtual DbSet<Main> Mains { get; set; }
        public virtual DbSet<Line_overall> Line_overall { get; set; }
        public virtual DbSet<Drill_Ron> Drill_Ron { get; set; }
        public virtual DbSet<Drill_RQ> Drill_RQ { get; set; }
    }
}
