//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetRoleBasedSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string User_name { get; set; }
        public string From_Track { get; set; }
        public string To_Track { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Status { get; set; }
        public string Final_Status { get; set; }
    }
}
