//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetRoleBasedSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQ_overall
    {
        public string X { get; set; }
        public Nullable<int> Y { get; set; }
        public string T { get; set; }
    }
}
